version: '3'
services:
  postgres:
    image: "postgres"
    environment:
      - POSTGRES_USER=dbpersons
      - POSTGRES_PASSWORD=dbpersons
      - POSTGRES_DB=dbpersons      
    ports:
      - "5432:5432"
    volumes:
      - ./migration/docker-database-initial.sql:/docker-entrypoint-initdb.d/docker-database-initial.sql